# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2
builds:
  - id: server_32
    main: ./server
    binary: server
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - arm
  - id: server_64
    main: ./server
    binary: server
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: server_64_full
    main: ./server
    binary: server/server
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: server-genCert_32
    main: ./server-genCert
    binary: bin/genCert
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - arm
  - id: server-genCert_64
    main: ./server-genCert
    binary: bin/genCert
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: server-genCert_64_full
    main: ./server-genCert
    binary: server/bin/genCert
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: launcher
    main: ./launcher
    binary: launcher
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: launcher_full
    main: ./launcher
    binary: launcher/launcher
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: launcher-agent
    main: ./launcher-agent
    binary: bin/agent
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: launcher-agent_full
    main: ./launcher-agent
    binary: launcher/bin/agent
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: launcher-config
    main: ./launcher-config
    binary: bin/config
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: launcher-config_full
    main: ./launcher-config
    binary: launcher/bin/config
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: launcher-config-admin
    main: ./launcher-config-admin
    binary: bin/config-admin
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: launcher-config-admin_full
    main: ./launcher-config-admin
    binary: launcher/bin/config-admin
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: launcher-config-admin-agent
    main: ./launcher-config-admin-agent
    binary: bin/config-admin-agent
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: launcher-config-admin-agent_full
    main: ./launcher-config-admin-agent
    binary: launcher/bin/config-admin-agent
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - id: all
    builds:
      - server_64_full
      - server-genCert_64_full
      - launcher_full
      - launcher-agent_full
      - launcher-config_full
      - launcher-config-admin_full
      - launcher-config-admin-agent_full
    name_template: >-
      {{- .ProjectName }}_full_
      {{- .RawVersion }}_
      {{- with .Os }}
        {{- if eq . "windows"}}win
        {{- else if eq . "darwin"}}mac
        {{- else }}{{ . }}
        {{- end }}
      {{- end}}
      {{- if eq .Arch "amd64" }}_x86-64
      {{- else if eq .Arch "arm64" }}_arm64
      {{- end }}
    files:
      - src: LICENSE
        dst: docs/LICENSE.txt
      - src: README.md
        dst: docs/README.txt
      - src: server/README.md
        dst: server/docs/README.txt
      - server/resources/config
      - server/resources/responses
      - src: launcher/README.md
        dst: launcher/docs/README.txt
      - src: launcher-config/README.md
        dst: launcher/docs/README-config.txt
      - launcher/resources
      - src: launcher-config/resources/cleanup.{{ if eq .Os "windows" }}bat{{ else }}sh{{ end }}
        dst: launcher/cleanup.bat
    format_overrides:
      - goos: windows
        format: zip
  - id: server
    builds: [ server_32, server-genCert_32, server_64, server-genCert_64 ]
    name_template: >-
      {{- .ProjectName }}_server_
      {{- .RawVersion }}_
      {{- with .Os }}
        {{- if eq . "windows"}}win
        {{- else if eq . "darwin"}}mac
        {{- else }}{{ . }}
        {{- end }}
      {{- end}}
      {{- if eq .Arch "386" }}_x86-32
      {{- else if eq .Arch "amd64" }}_x86-64
      {{- else if eq .Arch "arm" }}_arm32
      {{- else if eq .Arch "arm64" }}_arm64
      {{- end }}
    files:
      - src: server/resources/config
        dst: resources/config
      - src: server/resources/responses
        dst: resources/responses
      - src: LICENSE
        dst: docs/LICENSE.txt
      - src: README.md
        dst: docs/README.txt
    format_overrides:
      - goos: windows
        format: zip
  - id: launcher
    builds: [ launcher, launcher-agent, launcher-config, launcher-config-admin, launcher-config-admin-agent ]
    files:
      - src: launcher/resources
        dst: resources
      - src: LICENSE
        dst: docs/LICENSE.txt
      - src: launcher/README.md
        dst: docs/README.txt
      - src: launcher-config/README.md
        dst: docs/README-config.txt
      - src: launcher-config/resources/cleanup.{{ if eq .Os "windows" }}bat{{ else }}sh{{ end }}
        strip_parent: true
    name_template: >-
      {{- .ProjectName }}_launcher_
      {{- .RawVersion }}_
      {{- with .Os }}
        {{- if eq . "windows"}}win
        {{- else if eq . "darwin"}}mac
        {{- else }}{{ . }}
        {{- end }}
      {{- end}}
      {{- if eq .Arch "amd64" }}_x86-64
      {{- else if eq .Arch "arm64" }}_arm64
      {{- end }}
    format_overrides:
      - goos: windows
        format: zip
universal_binaries:
  - id: server_64
    name_template: 'server'
    replace: true
  - id: server-genCert_64
    name_template: 'bin/genCert'
    replace: true
  - id: server_64_full
    name_template: 'server/server'
    replace: true
  - id: server-genCert_64_full
    name_template: 'server/bin/genCert'
    replace: true
  - id: launcher
    name_template: 'launcher'
    replace: true
  - id: launcher-agent
    name_template: 'bin/agent'
    replace: true
  - id: launcher-config
    name_template: 'bin/config'
    replace: true
  - id: launcher-config-admin
    name_template: 'bin/config-admin'
    replace: true
  - id: launcher-config-admin-agent
    name_template: 'bin/config-admin-agent'
    replace: true
  - id: launcher_full
    name_template: 'launcher/launcher'
    replace: true
  - id: launcher-agent_full
    name_template: 'launcher/bin/agent'
    replace: true
  - id: launcher-config_full
    name_template: 'launcher/bin/config'
    replace: true
  - id: launcher-config-admin_full
    name_template: 'launcher/bin/config-admin'
    replace: true
  - id: launcher-config-admin-agent_full
    name_template: 'launcher/bin/config-admin-agent'
    replace: true
checksum:
  name_template: '{{ .ProjectName }}_{{ .RawVersion }}_checksums.txt'
signs:
  - artifacts: checksum
    cmd: gpg2
    args: [ "--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}" ]
