# yaml-language-server: $schema=https://taskfile.dev/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: '3'

dotenv: [ '.env', '{{.ENV}}/.env.', '{{.HOME}}/.env' ]

tasks:
  build:
    cmds:
      - goreleaser build --clean --snapshot
  release:
    cmds:
      - goreleaser release --clean --snapshot
  debug-prepare-server:
    deps: [ debug:prepare-server-base ]
    cmds:
      - build/server/bin/genCert{{exeExt}} -r
  build-config:
    internal: true
    cmds:
      - go build -o build/launcher/bin/config{exeExt}} ./launcher-config
  build-config-admin:
    cmds:
      - go build -o build/launcher/bin/config-admin{exeExt}} ./launcher-config-admin
  build-config-admin-agent:
    deps: [ build-config-admin ]
    cmds:
      - go build -o build/launcher/bin/config-admin-agent{exeExt}} ./launcher-config-admin-agent
  build-config-all:
    deps: [ build-config, build-config-admin-agent ]
includes:
  debug: ./Taskfile.{{if eq OS "windows"}}windows{{else}}unix{{end}}.yml