[Config]
# Executable to run (including arguments) to run first after the "Setting up..." line.
# The command must return a 0 exit code to continue. If you need to keep it running spawn a new detached process.
# Windows: Path names need to use double backslashes within single quotes or be within double quotes.
# Note: You may use environment variables.
SetupCommand = []
# Executable to run (including arguments) to run after SetupCommand, game has exited and everything has been reverted. It may run before if there is an error.
# Windows: Path names need to use double backslashes within single quotes or be within double quotes.
# Note: You may use environment variables.
RevertCommand = []

[Client]
# The path to the game launcher, the type (as seen next) or, if 'auto', then this priority applies:
# Windows:
# 1. Steam ('steam').
# 2. Microsoft Store - Xbox ('msstore'). Not available for AoM: RT.
# Linux:
# 1. Steam ('steam').
# 2. Steam with CrossOver ('steam_crossover').
# 3. Steam with Wine ('steam_wine').
# When using an official launcher, Config.Isolation.Metadata and Config.Isolation.Profiles must be 'required' or 'true'.
# Note: It is not recommended to use an executable that requires admin rights (but it is supported).
# Note 2: You may use environment variables.
Executable = 'auto'
# The arguments to pass to the client launcher if it is custom.
# {HostFilePath} will be replaced by the host file path.
# If using this variable, 'Config.CanAddHost' setting will be ignored.
# The host file follows the Windows system format.
# {CertFilePath} will be replaced by the certificate file path.
# If using this variable, 'Config.Certificate.CanTrustInPc' setting will be ignored.
# The format is the same as the server stored certificate.
# Windows: Path names need to use double backslashes within single quotes or be within double quotes.
# Note: You may use environment variables.
ExecutableArgs = []
# The path to the game installation path, if 'auto' and 'Executable' resolves to 'steam' or 'msstore' it will be detected automatically.
# If 'Executable' is a custom launcher, this is required to be set. Otherwise, this will be ignored.
# Used to find the game certificate certificate store, file "cacert.pem".
# Required that the game path can be found in all games except AoE I: DE and AoE IV: AE.
# Note: You may use environment variables.
Path = 'auto'

[Client.Isolation]
# Path to the game data, if 'auto' it will be detected automatically based on the game and Client.Executable.
# Linux Note: Required to be set to the path if Client.Executable is set to a custom launcher (and some isolation is enabled).
Path = 'auto'
# If 'required' it will resolve to 'true' if using the official launcher, 'false' otherwise.
# If it resolves to 'true', the launcher will isolate the metadata cache of the game, otherwise, it will be shared
# On AoE I this is always false as it does not store metadata.
Metadata = 'required'
# If 'required' it will resolve to 'true' if using the official launcher, 'false' otherwise.
# If it resolves to 'true', the launcher will isolate user profiles for the game, otherwise, it will be shared
# May cause issues with Steam Cloud or Xbox Cloud (depending on the game version) unless you disable cloud sync.
Profiles = 'required'