[Config]
# Executable to run (including arguments) to run first after the "Setting up..." line.
# The command must return a 0 exit code to continue. If you need to keep it running spawn a new detached process.
# Windows: Path names need to use double backslashes within single quotes or be within double quotes.
# Note: You may use environment variables.
SetupCommand = []
# Executable to run (including arguments) to run after SetupCommand, game has exited and everything has been reverted. It may run before if there is an error.
# Windows: Path names need to use double backslashes within single quotes or be within double quotes.
# Note: You may use environment variables.
RevertCommand = []

[Client]
# The path to the game launcher, if 'auto', the Steam and then the Xbox (Windows-only) one will be launched if found
# Use a path to the game launcher, 'steam' or 'msstore' (non AoM: RT and Windows-only) to use the default launcher.
# Note: It is not recommended to use an executable that requires admin rights (but it is supported).
# Linux Note: setting a custom launcher will make 'Config.IsolateMetadata' and 'Config.IsolateProfiles' act as 'false.
# Note 2: You may use environment variables.
Executable = 'auto'
# The arguments to pass to the client launcher if it is custom.
# {HostFilePath} will be replaced by the host file path.
# If using this variable, 'Config.CanAddHost' setting will be ignored.
# The host file follows the Windows system format.
# {CertFilePath} will be replaced by the certificate file path.
# If using this variable, 'Config.CanTrustCertificate' setting will be ignored.
# The format is the same as the server stored certificate.
# Windows: Path names need to use double backslashes within single quotes or be within double quotes.
# Note: You may use environment variables.
ExecutableArgs = []
# The path to the game installation path, if 'auto' and 'Executable' resolves to 'steam' or 'msstore' it will be detected automatically.
# If 'Executable' is a custom launcher, this is required to be set. Otherwise, this will be ignored.
# Used to find the game certificate certificate store, file "cacert.pem".
# Required that the game path can be found in all games except AoE I: DE.
# Note: You may use environment variables.
Path = 'auto'