name: ageLANServer
services:
  server:
    depends_on:
      battle-server-manager:
        condition: service_healthy
    volumes:
      - config_bs:/tmp/ageLANServer/battle-servers:ro
  battle-server-manager:
    environment:
      - GAME_ID=${GAME_ID:-}
      - LOG_SUBFOLDER=${LOG_SUBFOLDER:-}
      - BS_MANAGER_ARGS=${BS_MANAGER_ARGS:-}
    build:
      context: ../..
      dockerfile: tools/server-docker/battle-server-manager/Dockerfile
    depends_on:
      gen-cert:
        condition: service_completed_successfully
    volumes:
      - config_bs:/tmp/ageLANServer/battle-servers
      - config_bs_manager:/app/battle-server-manager/resources:ro
      - logs:/app/logs
      - certs:/app/server/resources/certificates:ro
      - type: bind
        source: "${BATTLE_SERVER_EXE}"
        target: /app/BattleServer.exe
        read_only: true
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f BattleServer.exe > /dev/null"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 10s
    network_mode: "host"
volumes:
  config_bs_manager:
  config_bs: