name: ageLANServer
services:
  gen-cert:
    environment:
      - GENCERT_ARGS=${GENCERT_ARGS:-}
    build:
      context: ../..
      dockerfile: tools/server-docker/genCert/Dockerfile
    volumes:
      - certs:/app/server/resources/certificates
    network_mode: none
    command: --ignoreIfExisting
  server:
    environment:
      - GAME_ID=${GAME_ID:-}
      - LOG_SUBFOLDER=${LOG_SUBFOLDER:-}
      - SERVER_ARGS=${SERVER_ARGS:-}
    build:
      context: ../..
      dockerfile: tools/server-docker/server/Dockerfile
    depends_on:
      gen-cert:
        condition: service_completed_successfully
    volumes:
      - config_server:/app/server/resources/config:ro
      - logs:/app/logs
      - certs:/app/server/resources/certificates:ro
    command: $SERVER_ARGS
    network_mode: "host"
volumes:
  certs:
  config_server:
  logs: